chore(): add ionic issue bot
ionic-team/stencil-ds-output-targets pull request #240
Opened 2022-03-19 18:31 UTC by sean-perkins

Adds the Ionitron (ionic issue bot) to the repository to aid with repository management.

2022-03-21 12:22 UTC, rwaskiewicz requested changes
Two small asks before we land this:

1. We should document (internally) how we expect the Framework + Stencil team should triage issues - what labels to apply/when, etc. I'd be willing to bet there's been some divergence in our respective repository's processes.  That's fine (no complaints there!), but I want to make sure there's a reference point for both teams to understand expectations around handling issues in the repo
2. When we finalize the labels/process described here, we'll need to make sure these labels get added to https://github.com/ionic-team/stencil-ds-output-targets/labels

This looks great though! Thanks sooo much for doing this 🙏

2022-03-24 17:28 UTC, sean-perkins commented
Stale section has been removed. I also dropped a notion doc in our internal channel for the initial process.

2022-03-24 17:49 UTC, amandaesmith3 approved these changes

2022-03-24 18:45 UTC, rwaskiewicz commented on .github/ionic-issue-bot.yml
> +    - label: "ionitron: needs reproduction"
Does this label / action conflict with the one below? https://github.com/ionic-team/stencil-ds-output-targets/pull/240/files#diff-5ab3559a040d16f7b7db847060a448dddde18e8320e13b8d5737c31672708375R66

The message associated with this action seems to imply the issue will stay open (so long as they provide a repro), whereas the one below closes the issue. Am I reading this right?

2022-03-24 18:46 UTC, rwaskiewicz commented
@sean-perkins I think we're in a good place to add the labels in the PR to https://github.com/ionic-team/stencil-ds-output-targets/labels. Thoughts?

2022-03-24 18:50 UTC, sean-perkins commented
Yep, I can add those labels now 👍

2022-03-24 18:51 UTC, rwaskiewicz commented on .github/ionic-issue-bot.yml
> +    - label: "ionitron: needs reproduction"
👍 Makes sense to me - thanks! (serious brain fog day 🙃)

2022-03-24 18:51 UTC, rwaskiewicz approved these changes
Approved, Sean's adding the labels now

2022-03-24 18:53 UTC, merged