fix(angular): type resolution with strict templates
ionic-team/stencil-ds-output-targets pull request #266
Opened 2022-06-17 16:36 UTC by sean-perkins

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally for affected output targets
- [ ] Tests (`npm test`) were run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

The generated Angular proxies do not take advantage of the new custom event interfaces as of Stencil 2.16.0. 

Issue URL: #209

## What is the new behavior?

- Requires a peer dependency of `@stencil/core@2.16.0`
- Generates Angular output events with the new custom event interfaces
- Angular strict templates should no longer complain for output bindings

## Does this introduce a breaking change?

- [x] Yes
- [ ] No

Requires Stencil 2.16.0. Developers will need to update their library dependency version to minimally `2.16.0`. 

## Other information

2022-07-09 02:08 UTC, sean-perkins commented
This PR is a prerequisite to https://github.com/ionic-team/ionic-framework/pull/25502.

2022-07-19 13:03 UTC, rwaskiewicz requested changes

2022-07-19 13:03 UTC, rwaskiewicz commented on packages/angular-output-target/src/output-angular.ts
> +        }/${component.tagName}.js';`;
Double checking - was this new white space intentional?

2022-07-28 16:16 UTC, sean-perkins commented on packages/angular-output-target/src/generate-angular-component.ts
> +    ''
Was used to create an empty new line when the output bindings are written to file, but I can see where that is very unclear with including an empty string in an array. 

I've changed this approach to remove the empty string and explicitly write a new line when pushing the output bindings to our `lines` array (which is later written to file).

2022-08-01 19:40 UTC, rwaskiewicz approved these changes

2022-11-03 21:48 UTC, sean-perkins commented
Closing this PR in favor of https://github.com/ionic-team/stencil-ds-output-targets/pull/308. Will open that PR for review after generating a dev-build and doing one more pass of testing.

2022-11-03 21:48 UTC, closed without merging