fix: enable event names with special characters
ionic-team/stencil-ds-output-targets pull request #474
Opened 2024-09-09 20:10 UTC by alexprudhomme

fix #473 

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`npm run build`) was run locally for affected output targets
- [ ] Tests (`npm test`) were run locally and passed
- [ ] Prettier (`npm run prettier`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue URL:

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2024-09-11 15:36 UTC, tanner-reits requested changes
@alexprudhomme I tested this out with your `/` event naming, but doesn't seem to work with that convention. As far as I know, React requires strict camel-casing for event handlers, so if you wanted to have event names with a `/` in them, you would need to update the logic [here](https://github.com/ionic-team/stencil-ds-output-targets/blob/main/packages/react-output-target/src/react-output-target/utils/string-utils.ts#L10) to also perform those replacements

2024-09-16 19:49 UTC, alexprudhomme commented
> @alexprudhomme I tested this out with your `/` event naming, but doesn't seem to work with that convention. As far as I know, React requires strict camel-casing for event handlers, so if you wanted to have event names with a `/` in them, you would need to update the logic [here](https://github.com/ionic-team/stencil-ds-output-targets/blob/main/packages/react-output-target/src/react-output-target/utils/string-utils.ts#L10) to also perform those replacements

Hey, thanks for the useful tip. I changed the implementation and added a test. Let me know if you need anything more.

2024-09-17 16:26 UTC, tanner-reits requested changes
@alexprudhomme Functionality looks good! Only thing I would like to see changed is to leave the `kebabToCamelCase` function as it was (in case we have need for that utility later), and move the `/` replacement to a separate utility function that can be called in `eventListenerName`.

2024-09-18 13:37 UTC, tanner-reits requested changes
Just some naming fixes, then g2g

2024-09-18 13:37 UTC, tanner-reits commented on packages/react-output-target/src/react-output-target/utils/string-utils.ts
> +const dashesToCamelCase = (str: string) => str.replace(/\/([a-z])/g, (_, letter) => letter.toUpperCase());
```suggestion
const slashesToCamelCase = (str: string) => str.replace(/\/([a-z])/g, (_, letter) => letter.toUpperCase());
```

2024-09-18 13:37 UTC, tanner-reits commented on packages/react-output-target/src/react-output-target/utils/string-utils.ts
> +  return kebabToCamelCase(`on-${dashedConverted}`);
```suggestion
  const slashesConverted = slashesToCamelCase(eventName);
  return kebabToCamelCase(`on-${slashesConverted}`);
```

2024-09-18 14:58 UTC, tanner-reits approved these changes

2024-09-18 15:26 UTC, merged

2024-10-21 16:10 UTC, alexprudhomme commented
@tanner-reits 
Hi, 
Will you be able to make a release soon with this fix ? Last one was on august 28th. 
Thanks !

2024-10-22 01:14 UTC, christian-bromann commented
@alexprudhomme I am working on it as we speak.