fix(angular): enable event names with forward slash
ionic-team/stencil-ds-output-targets pull request #482
Opened 2024-09-16 20:05 UTC by alexprudhomme

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`npm run build`) was run locally for affected output targets
- [ ] Tests (`npm test`) were run locally and passed
- [ ] Prettier (`npm run prettier`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue URL:

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2024-09-17 16:45 UTC, tanner-reits requested changes
One little comment update, then should be good!

2024-09-17 16:45 UTC, tanner-reits commented on packages/angular-output-target/src/generate-angular-component.ts
>        // If an event name includes a dash, we need to wrap it in quotes.
```suggestion
      // If an event name includes a dash or a forward slash, we need to wrap it in quotes.
```

2024-09-18 13:37 UTC, tanner-reits approved these changes

2024-09-18 15:27 UTC, tanner-reits commented
@alexprudhomme Can you actually add a test for this to [this file](https://github.com/ionic-team/stencil-ds-output-targets/blob/main/packages/angular-output-target/__tests__/generate-angular-component.spec.ts)?

2024-09-18 20:16 UTC, alexprudhomme commented
done. thanks for merging these !

2024-09-18 21:53 UTC, brandyscarney approved these changes

2024-09-18 22:13 UTC, merged